from pathlib import Path
p=Path('/mnt/data/horizon_work/bot.py'); s=p.read_text()
needle='@rpg_root.command(name="mine")\nasync def rpg_mine(ctx):\n    await _rpg_delete(ctx); ok,msg=await bot.rpg.gather(ctx.guild.id,ctx.author.id,"mine"); await _rpg_action_panel(ctx, "Mining", msg, ok)\n\n\n'
if needle not in s: raise SystemExit('mine missing')
add='''@rpg_root.command(name="professions", aliases=["prof"])\nasync def rpg_professions(ctx):\n    await _rpg_delete(ctx); rows=await bot.rpg.professions(ctx.guild.id,ctx.author.id)\n    text="\\n".join(f"**{name.title()}** — Lv **{level}** • {xp} XP" for name,level,xp in rows)\n    await _rpg_action_panel(ctx,"🛠️ Professions",text+"\\n\\nGathering Lv 10+ yields an extra material.",True)\n\n@rpg_root.command(name="economy", aliases=["wallet","econ"])\nasync def rpg_economy(ctx):\n    await _rpg_delete(ctx); data=await bot.rpg.economy_summary(ctx.guild.id,ctx.author.id)\n    if not data: await _rpg_action_panel(ctx,"Economy","Create a hero first.",False); return\n    text=f"💰 Gold: **{data['gold']}**\\n💎 Gems: **{data['gems']}**\\n\\nGold earned: **{data['earned']}**\\nGold spent: **{data['spent']}**\\nEconomy events: **{data['events']}**\\nMarket sales: **{data['market_sold']}**"\n    await _rpg_action_panel(ctx,"📊 Personal Economy",text,True)\n\n'''
s=s.replace(needle,needle+add,1)
needle2='@rpg_root.command(name="unequip-pet", aliases=["unequippet","pet-unequip"])\nasync def rpg_unequip_pet(ctx):\n    await _rpg_delete(ctx); ok,msg=await bot.rpg.unequip_pet(ctx.guild.id,ctx.author.id); await _rpg_action_panel(ctx,"Pet Equipment",msg,ok)\n\n'
if needle2 not in s: raise SystemExit('pet missing')
add2='''@rpg_root.command(name="petfeed", aliases=["feedpet","pet-feed"])\nasync def rpg_pet_feed(ctx, pet_id:int=0):\n    await _rpg_delete(ctx); ok,msg=await bot.rpg.pet_feed(ctx.guild.id,ctx.author.id,pet_id or None); await _rpg_action_panel(ctx,"🐾 Pet Care",msg,ok)\n\n@rpg_root.command(name="petcollection", aliases=["petdex","pet-collection"])\nasync def rpg_pet_collection(ctx):\n    await _rpg_delete(ctx); rows=await bot.rpg.pet_collection(ctx.guild.id,ctx.author.id)\n    known={r[0]:r for r in rows}; lines=[]\n    for species,data in PET_SPECIES.items():\n        lines.append(("🟢" if species in known else "⚪")+f" **{species}** — {data['rarity'].title()}"+(f" • seen {known[species][1]}x" if species in known else " • undiscovered"))\n    pages=_rpg_pages("🐾 Pet Codex",[(i,"\\n".join(lines[i*8:(i+1)*8])) for i in range((len(lines)+7)//8)],page_size=1,icon="🐾",formatter=lambda x:x[1])\n    await _rpg_panel(ctx,pages)\n\n'''
s=s.replace(needle2,needle2+add2,1)
needle3='@rpg_root.command(name="housing")\nasync def rpg_housing(ctx):\n    await _rpg_delete(ctx); h=await bot.rpg.housing(ctx.guild.id,ctx.author.id)\n    await _rpg_action_panel(ctx,"🏠 Your Housing",f"**{h[\'house_key\'].replace(\'_\',\' \').title()}**\\nLevel **{h[\'level\']}** • XP **{h[\'xp\']}**\\nStorage bonus **+{h[\'storage_bonus\']}** • Comfort **{h[\'comfort\']}",True)\n\n'
if needle3 not in s: raise SystemExit('housing missing')
add3='''@rpg_root.command(name="house-upgrade", aliases=["upgradehouse","houseupgrade"])\nasync def rpg_house_upgrade(ctx):\n    await _rpg_delete(ctx); ok,msg=await bot.rpg.housing_upgrade(ctx.guild.id,ctx.author.id); await _rpg_action_panel(ctx,"🏠 Home Upgrade",msg,ok)\n\n@rpg_root.command(name="life-path", aliases=["lifepath","path"])\nasync def rpg_life_path(ctx, path:str=""):\n    await _rpg_delete(ctx)\n    if not path: await _rpg_action_panel(ctx,"🌱 Life Path","Choose: adventurer, merchant, craftsman, scholar, ruler.",False); return\n    ok,msg=await bot.rpg.set_life_path(ctx.guild.id,ctx.author.id,path); await _rpg_action_panel(ctx,"🌱 Life Path",msg,ok)\n\n'''
s=s.replace(needle3,needle3+add3,1)
s=s.replace('`!rpg shop` / `buy` / `sell` / `craft` / `market` — economy','`!rpg shop` / `buy` / `sell` / `recipes` / `craft` / `gather` / `mine` / `fish` / `market` / `economy` — economy + professions')
s=s.replace('`!rpg pet` — equipped companion\n`!rpg equip-pet <pet_id>` — switch companions','`!rpg pet` — equipped companion\n`!rpg pets` / `petcollection` — collection + codex\n`!rpg petfeed [pet_id]` — bond/XP pet care\n`!rpg equip-pet <pet_id>` — switch companions')
s=s.replace('`!rpg party ...` / `guild ...` / `kingdom ...` — multiplayer systems','`!rpg party ...` / `guild ...` / `kingdom ...` / `bounty ...` — multiplayer systems\n`!rpg housing` / `house-upgrade` / `life-path` — player life systems')
p.write_text(s)
