import React,{useEffect,useRef,useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';
const W=3600,H=2400;
const zones=[{id:'north',name:'Northreach',x:500,y:520,r:310},{id:'wild',name:'Whispering Wilds',x:1550,y:480,r:520},{id:'ashen',name:'Ashen Pass',x:2800,y:620,r:420},{id:'ruins',name:'Sunken Ruins',x:2850,y:1740,r:430},{id:'steppe',name:'Golden Steppe',x:1350,y:1760,r:470}];
const foes=[{name:'Fang Wolf',x:920,y:820,lvl:3,hp:42,max:42},{name:'Moss Warden',x:1840,y:930,lvl:7,hp:88,max:88},{name:'Ash Drake',x:2960,y:840,lvl:11,hp:130,max:130},{name:'Ruin Sentinel',x:2470,y:1640,lvl:12,hp:160,max:160}];
const npcs=[{name:'Mira',x:510,y:590,text:'The crystal gate reacted when you arrived.'},{name:'Kael',x:620,y:470,text:'Bring me ember ore. I can forge something worthy.'},{name:'Selene',x:1010,y:520,text:'The forest has started moving again. Watch the trees.'}];
const loot=[{name:'Moonleaf',x:720,y:1040},{name:'Ember Ore',x:2550,y:510},{name:'Ancient Sigil',x:2720,y:1900},{name:'Sunsteel Shard',x:1470,y:2050}];
const d=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),cl=(v,a,b)=>Math.max(a,Math.min(b,v));
const waterAt=(x,y)=>x>2080+Math.sin(y*.003)*85;
const blockedAt=(x,y)=>waterAt(x,y);
function App(){const[c,setC]=useState({x:500,y:640,hp:100,maxHp:100,mp:60,maxMp:60,lvl:1,xp:0,gold:120,atk:12,spd:235});const[k,setK]=useState({});const[paused,setPaused]=useState(false);const[combat,setCombat]=useState(null);const[tab,setTab]=useState('quest');const[log,setLog]=useState(['You woke beside the Northreach gate.','Mira noticed the gate respond to you.']);const[notice,setNotice]=useState('WASD to move • SHIFT to sprint • E to interact • SPACE to attack');const[map,setMap]=useState(false);const ref=useRef(null),kr=useRef({}),touch=useRef({x:0,y:0,active:false,sprint:false});
useEffect(()=>{kr.current=k},[k]);useEffect(()=>{const down=e=>{if(['w','a','s','d','shift','arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase()))e.preventDefault();setK(x=>({...x,[e.key.toLowerCase()]:1}))},up=e=>setK(x=>({...x,[e.key.toLowerCase()]:0}));addEventListener('keydown',down);addEventListener('keyup',up);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up)}},[]);
useEffect(()=>{let last=performance.now(),id;const loop=t=>{const dt=Math.min(.035,(t-last)/1000);last=t;if(!paused&&!combat){let x=0,y=0,q=kr.current;if(q.w||q.arrowup)y--;if(q.s||q.arrowdown)y++;if(q.a||q.arrowleft)x--;if(q.d||q.arrowright)x++;if(touch.current.active){x+=touch.current.x;y+=touch.current.y}if(x||y){let m=Math.hypot(x,y),sp=c.spd*((q.shift||touch.current.sprint)?1.65:1);setC(p=>{const nx=cl(p.x+x/m*sp*dt,50,W-50),ny=cl(p.y+y/m*sp*dt,50,H-50);if(blockedAt(nx,ny))return p;return {...p,x:nx,y:ny}})}}id=requestAnimationFrame(loop)};id=requestAnimationFrame(loop);return()=>cancelAnimationFrame(id)},[paused,combat,c.spd]);
useEffect(()=>{const f=foes.find(x=>d(c,x)<70&&x.hp>0);if(f&&!combat){setCombat({...f});setNotice(f.name+' engaged you.')}} ,[c.x,c.y]);
useEffect(()=>{const n=npcs.find(x=>d(c,x)<80),l=loot.find(x=>d(c,x)<65);if(!combat)setNotice(n?n.name+' • press E to talk':l?l.name+' • press E to collect':'Explore the frontier freely.')},[c.x,c.y,combat]);
useEffect(()=>{const h=e=>{if(e.key.toLowerCase()==='e'&&!combat){const n=npcs.find(x=>d(c,x)<80),l=loot.find(x=>d(c,x)<65);if(n){setLog(x=>(n.name+': “'+n.text+'”')? [n.name+': “'+n.text+'”',...x].slice(0,8):x);setC(p=>({...p,xp:p.xp+25}));return}if(l){setLog(x=>(['Collected '+l.name+'.',...x]).slice(0,8));setNotice(l.name+' added to your bag.');}}};addEventListener('keydown',h);return()=>removeEventListener('keydown',h)},[c,combat]);
useEffect(()=>{const h=e=>{if(e.key===' '&&combat){setCombat(x=>({...x,hp:Math.max(0,x.hp-c.atk)}));setC(p=>({...p,mp:Math.max(0,p.mp-2),hp:Math.max(0,p.hp-(4+combat.lvl))}))}if(e.key.toLowerCase()==='1'&&combat&&c.mp>=15){setCombat(x=>({...x,hp:Math.max(0,x.hp-(c.atk+22))}));setC(p=>({...p,mp:p.mp-15}))}if(e.key==='Escape'&&combat){setCombat(null);setC(p=>({...p,x:p.x-90}));setNotice('You escaped the encounter.')}};addEventListener('keydown',h);return()=>removeEventListener('keydown',h)},[combat,c]);
useEffect(()=>{if(combat&&combat.hp<=0){const r=30+combat.lvl*10;setC(p=>{const xp=p.xp+r,next=p.lvl*100;return{...p,xp:xp>=next?xp-next:xp,lvl:xp>=next?p.lvl+1:p.lvl,gold:p.gold+r,hp:Math.min(p.maxHp,p.hp+15)}});setLog(x=>(['Defeated '+combat.name+'. +'+r+' gold.',...x]).slice(0,8));setCombat(null);setNotice('Victory. The frontier is still waiting.')}},[combat]);
useEffect(()=>{const cv=ref.current,ctx=cv.getContext('2d');let id;const draw=()=>{const w=cv.clientWidth,h=cv.clientHeight,dpr=Math.min(2,window.devicePixelRatio||1);if(cv.width!==Math.floor(w*dpr)||cv.height!==Math.floor(h*dpr)){cv.width=Math.floor(w*dpr);cv.height=Math.floor(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=false;
const mobile=window.matchMedia('(max-width:720px),(orientation:landscape) and (max-height:700px)').matches;const zoom=mobile?1.55:1.15;const viewW=w/zoom,viewH=h/zoom;const camX=cl(c.x-viewW/2,0,W-viewW),camY=cl(c.y-viewH/2,0,H-viewH);const X=v=>(v-camX)*zoom,Y=v=>(v-camY)*zoom;ctx.fillStyle='#78a968';ctx.fillRect(0,0,w,h);
const tile=32,tx0=Math.floor(camX/tile)-1,tx1=Math.ceil((camX+viewW)/tile)+1,ty0=Math.floor(camY/tile)-1,ty1=Math.ceil((camY+viewH)/tile)+1;const hash=(x,y)=>{const n=Math.sin(x*127.1+y*311.7)*43758.5453;return n-Math.floor(n)};
const river=(wx,wy)=>waterAt(wx,wy);const road=(wx,wy)=>{const main=Math.abs(wy-(760+Math.sin(wx*.0018)*55))<34;const town=Math.abs(wx-590)<30&&wy>470&&wy<1050;return main||town};
for(let yy=ty0;yy<=ty1;yy++)for(let xx=tx0;xx<=tx1;xx++){const wx=xx*tile,wy=yy*tile,px=X(wx),py=Y(wy),tw=tile*zoom+1;if(river(wx,wy)){ctx.fillStyle='#4f8fa4';ctx.fillRect(px,py,tw,tw);ctx.fillStyle='#73b4bf';if(hash(xx,yy)>.35)ctx.fillRect(px+5*zoom,py+12*zoom,12*zoom,2*zoom)}else if(road(wx,wy)){ctx.fillStyle='#c5ad78';ctx.fillRect(px,py,tw,tw);ctx.fillStyle='#d9c38e';if(hash(xx,yy)>.45)ctx.fillRect(px+8*zoom,py+19*zoom,5*zoom,2*zoom)}else{ctx.fillStyle=hash(xx,yy)>.5?'#79ad69':'#74a765';ctx.fillRect(px,py,tw,tw);ctx.fillStyle='#5d925b';const g=hash(xx+8,yy+3);ctx.fillRect(px+g*tw*.8,py+5*zoom,2*zoom,4*zoom);if(hash(xx+4,yy+7)>.82){ctx.fillStyle='#e7d16b';ctx.fillRect(px+20*zoom,py+9*zoom,3*zoom,3*zoom);ctx.fillStyle='#d8877d';ctx.fillRect(px+24*zoom,py+8*zoom,2*zoom,4*zoom)}}}
const tree=(wx,wy)=>{if(d({x:wx,y:wy},c)<55)return;const x=X(wx),y=Y(wy);ctx.fillStyle='#5a3b2a';ctx.fillRect(x-4*zoom,y+7*zoom,8*zoom,14*zoom);ctx.fillStyle='#234d35';ctx.fillRect(x-13*zoom,y-11*zoom,26*zoom,18*zoom);ctx.fillStyle='#327047';ctx.fillRect(x-10*zoom,y-17*zoom,20*zoom,22*zoom);ctx.fillStyle='#4b8950';ctx.fillRect(x-5*zoom,y-21*zoom,10*zoom,9*zoom)};
for(let i=0;i<130;i++){const wx=(i*173%3200)+100,wy=(i*97%2050)+100;if(!river(wx,wy)&&!road(wx,wy))tree(wx,wy)}
const rock=(wx,wy)=>{const x=X(wx),y=Y(wy);ctx.fillStyle='#66706a';ctx.fillRect(x-7*zoom,y-4*zoom,14*zoom,8*zoom);ctx.fillStyle='#89928b';ctx.fillRect(x-4*zoom,y-6*zoom,7*zoom,3*zoom)};for(let i=0;i<45;i++){const wx=(i*257%3300)+80,wy=(i*149%2150)+80;if(!river(wx,wy)&&!road(wx,wy))rock(wx,wy)}
const house=(wx,wy,name)=>{const x=X(wx),y=Y(wy),ww=88*zoom,hh=62*zoom;ctx.fillStyle='#b87955';ctx.fillRect(x-ww/2,y-hh/2,ww,hh);ctx.fillStyle='#6d3c3a';ctx.beginPath();ctx.moveTo(x-ww*.58,y-hh*.5);ctx.lineTo(x,y-hh*.95);ctx.lineTo(x+ww*.58,y-hh*.5);ctx.closePath();ctx.fill();ctx.fillStyle='#e5c36c';ctx.fillRect(x-27*zoom,y-10*zoom,13*zoom,13*zoom);ctx.fillRect(x+14*zoom,y-10*zoom,13*zoom,13*zoom);ctx.fillStyle='#354654';ctx.fillRect(x-9*zoom,y+3*zoom,18*zoom,28*zoom);ctx.fillStyle='#2d3b38';ctx.font='bold '+Math.max(7,8*zoom)+'px monospace';ctx.textAlign='center';ctx.fillText(name,x,y-hh*.9);ctx.textAlign='left'};house(500,430,'NORTHREACH');house(730,560,'INN');house(350,720,'GUILD');
const npc=n=>{const x=X(n.x),y=Y(n.y);ctx.fillStyle='#293b50';ctx.fillRect(x-5*zoom,y-1*zoom,10*zoom,15*zoom);ctx.fillStyle='#f0b981';ctx.fillRect(x-5*zoom,y-13*zoom,10*zoom,10*zoom);ctx.fillStyle='#5a352d';ctx.fillRect(x-6*zoom,y-15*zoom,12*zoom,5*zoom);ctx.fillStyle='#fff';ctx.font='bold '+Math.max(7,8*zoom)+'px monospace';ctx.fillText(n.name,x+9*zoom,y-10*zoom)};npcs.forEach(npc);
const item=l=>{const x=X(l.x),y=Y(l.y);ctx.fillStyle='#f5d36c';ctx.fillRect(x-4*zoom,y-4*zoom,8*zoom,8*zoom);ctx.fillStyle='#fff4ad';ctx.fillRect(x-2*zoom,y-7*zoom,4*zoom,4*zoom)};loot.forEach(item);
const enemy=f=>{if(f.hp<=0)return;const x=X(f.x),y=Y(f.y);ctx.fillStyle='#38253a';ctx.fillRect(x-7*zoom,y-1*zoom,14*zoom,15*zoom);ctx.fillStyle='#9d4054';ctx.fillRect(x-9*zoom,y-12*zoom,18*zoom,12*zoom);ctx.fillStyle='#f5d56e';ctx.fillRect(x-5*zoom,y-9*zoom,3*zoom,3*zoom);ctx.fillRect(x+2*zoom,y-9*zoom,3*zoom,3*zoom)};foes.forEach(enemy);
const px=X(c.x),py=Y(c.y);ctx.fillStyle='#202d4a';ctx.fillRect(px-8*zoom,py+4*zoom,16*zoom,17*zoom);ctx.fillStyle='#3d8dcc';ctx.fillRect(px-7*zoom,py-7*zoom,14*zoom,13*zoom);ctx.fillStyle='#f0b981';ctx.fillRect(px-6*zoom,py-18*zoom,12*zoom,11*zoom);ctx.fillStyle='#26304a';ctx.fillRect(px-7*zoom,py-21*zoom,14*zoom,6*zoom);ctx.fillStyle='#fff';ctx.fillRect(px-4*zoom,py-15*zoom,2*zoom,2*zoom);ctx.fillRect(px+2*zoom,py-15*zoom,2*zoom,2*zoom);ctx.fillStyle='#7de5ff';ctx.fillRect(px-10*zoom,py+23*zoom,20*zoom,2*zoom);
id=requestAnimationFrame(draw)};id=requestAnimationFrame(draw);return()=>cancelAnimationFrame(id)},[c]);return <div className="game"><canvas ref={ref}/><div className="top"><b>HORIZON <span>FRONTIER</span></b><div>● WORLD ONLINE　 DAY 01　18:00</div><aside><button onClick={()=>setPaused(!paused)}>{paused?'RESUME':'PAUSE'}</button><button onClick={()=>setMap(1)}>WORLD MAP</button></aside></div>
<div className="hud left"><div className="avatar">A</div><h3>Aeris</h3><small>ADVENTURER • LEVEL {c.lvl}</small><label>HP {c.hp}/{c.maxHp}</label><i><em style={{width:c.hp/c.maxHp*100+'%'}}/></i><label>MP {c.mp}/{c.maxMp}</label><i><em className="mp" style={{width:c.mp/c.maxMp*100+'%'}}/></i><div className="stats"><span>ATK <b>{c.atk}</b></span><span>SPD <b>{c.spd}</b></span><span>G <b>{c.gold}</b></span></div></div>
<div className="hud right"><nav><button className={tab==='quest'?'on':''} onClick={()=>setTab('quest')}>QUEST</button><button className={tab==='bag'?'on':''} onClick={()=>setTab('bag')}>BAG</button><button className={tab==='log'?'on':''} onClick={()=>setTab('log')}>LOG</button></nav>{tab==='quest'&&<section><small>MAIN QUEST</small><h2>The First Footstep</h2><p>Explore Northreach, meet the frontier and uncover what woke the gate.</p><div className="progress"><em style={{width:Math.min(100,c.xp/100*100)+'%'}}/></div></section>}{tab==='bag'&&<section>{['Rustbound Blade ×1','Small Potion ×3','Moonleaf ×1','Ember Ore ×1'].map(x=><p className="item" key={x}>{x}</p>)}</section>}{tab==='log'&&<section>{log.map((x,i)=><p className="entry" key={i}>{x}</p>)}</section>} </div>
<div className="notice">{notice}</div><div className="mobile-controls"><div className="joystick" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);touch.current.active=true;const r=e.currentTarget.getBoundingClientRect();const update=ev=>{const dx=ev.clientX-(r.left+r.width/2),dy=ev.clientY-(r.top+r.height/2),m=Math.max(1,Math.hypot(dx,dy)),max=r.width*.34,rx=Math.max(-1,Math.min(1,dx/max)),ry=Math.max(-1,Math.min(1,dy/max));touch.current.x=rx;touch.current.y=ry;const knob=e.currentTarget.querySelector('span');if(knob)knob.style.transform='translate(calc(-50% + '+(rx*max)+'px),calc(-50% + '+(ry*max)+'px))'};update(e);e.currentTarget.onpointermove=update}} onPointerUp={e=>{touch.current.active=false;touch.current.x=0;touch.current.y=0;const knob=e.currentTarget.querySelector('span');if(knob)knob.style.transform='translate(-50%,-50%)';e.currentTarget.onpointermove=null}} onPointerCancel={e=>{touch.current.active=false;touch.current.x=0;touch.current.y=0}}><span/></div><div className="action-pad"><button onPointerDown={()=>{touch.current.sprint=true}} onPointerUp={()=>{touch.current.sprint=false}}>SPRINT</button><button className="attack" onPointerDown={()=>{if(combat){setCombat(x=>({...x,hp:Math.max(0,x.hp-c.atk)}));setC(p=>({...p,mp:Math.max(0,p.mp-2),hp:Math.max(0,p.hp-(4+(combat?.lvl||1)))}))}}}>ATTACK</button><button onPointerDown={()=>{if(combat&&c.mp>=15){setCombat(x=>({...x,hp:Math.max(0,x.hp-(c.atk+22))}));setC(p=>({...p,mp:p.mp-15}))}}}>SKILL</button><button onPointerDown={()=>{if(!combat){const n=npcs.find(x=>d(c,x)<80),l=loot.find(x=>d(c,x)<65);if(n){setLog(x=>[n.name+': “'+n.text+'”',...x].slice(0,8));setC(p=>({...p,xp:p.xp+25}))}else if(l){setLog(x=>['Collected '+l.name+'.',...x].slice(0,8));setNotice(l.name+' added to your bag.')}}}}>INTERACT</button></div></div>{combat&&<div className="combat"><small>ENCOUNTER • LEVEL {combat.lvl}</small><h2>{combat.name}</h2><div className="enemy"><em style={{width:combat.hp/combat.max*100+'%'}}/></div><p>SPACE attack　1 skill　ESC flee</p><button className="mobile-flee" onClick={()=>{setCombat(null);setC(p=>({...p,x:p.x-90}));setNotice('You escaped the encounter.')}}>FLEE</button></div>}
{paused&&<div className="pause">PAUSED</div>}{map&&<div className="modal" onClick={()=>setMap(false)}><div className="mapbox" onClick={e=>e.stopPropagation()}><header><h2>The Horizon Frontier</h2><button onClick={()=>setMap(false)}>CLOSE</button></header><div className="worldmap">{zones.map(z=><span key={z.id} style={{left:z.x/W*100+'%',top:z.y/H*100+'%'}}>{z.name}</span>)}<b style={{left:c.x/W*100+'%',top:c.y/H*100+'%'}}>YOU</b></div></div></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);